// app/layout.tsx
import { ClerkProvider } from '@clerk/nextjs';
import {  neobrutalism } from '@clerk/themes'
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Next.js App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider 
    appearance={{
      baseTheme: neobrutalism,
    }}>
      <html lang="en">
        <body >
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}